<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-GDVE49C" ignored="5" name="packageExample" tests="9" failures="3" timestamp="04 Jun 2020 19:14:23 GMT" time="2.344" errors="0">
  <testcase name="assertAdditionTest" time="0.04" classname="testng.CalculatorTestNgTest"/>
  <testcase name="assertDivisionTest" time="0.008" classname="testng.CalculatorTestNgTest">
    <failure type="java.lang.AssertionError" message="Division of two numbers is not correct expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: Division of two numbers is not correct expected [2] but found [1]
	at testng.CalculatorTestNgTest.assertDivisionTest(CalculatorTestNgTest.java:44)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- assertDivisionTest -->
  <testcase name="assertMultiplicationTest" time="0.008" classname="testng.CalculatorTestNgTest">
    <failure type="java.lang.AssertionError" message="Multiplication of two numbers is not correct expected [20] but found [25]">
      <![CDATA[java.lang.AssertionError: Multiplication of two numbers is not correct expected [20] but found [25]
	at testng.CalculatorTestNgTest.assertMultiplicationTest(CalculatorTestNgTest.java:58)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- assertMultiplicationTest -->
  <testcase name="assertSubstractionTest" time="0.011" classname="testng.CalculatorTestNgTest"/>
  <testcase name="assertStatementDownloadTest" time="0.004" classname="testng.TestAttributesExample"/>
  <testcase name="assertStatementDownloadTest" time="0.008" classname="testng.TestAttributesExample"/>
  <testcase name="assertStatementDownloadTest" time="0.008" classname="testng.TestAttributesExample"/>
  <testcase name="assertTimeOutTest" time="2.049" classname="testng.TestAttributesExample">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- assertTimeOutTest -->
  <testcase name="assertValidExceptionTest" time="0.008" classname="testng.TestAttributesExample"/>
  <testcase name="assertTestE" time="0.0" classname="testng.TestAttributesExample">
    <ignored/>
  </testcase> <!-- assertTestE -->
  <testcase name="assertTestB" time="0.0" classname="testng.TestAttributesExample">
    <ignored/>
  </testcase> <!-- assertTestB -->
  <testcase name="assertTestC" time="0.0" classname="testng.TestAttributesExample">
    <ignored/>
  </testcase> <!-- assertTestC -->
  <testcase name="assertTestD" time="0.0" classname="testng.TestAttributesExample">
    <ignored/>
  </testcase> <!-- assertTestD -->
  <testcase name="assertTestA" time="0.0" classname="testng.TestAttributesExample">
    <ignored/>
  </testcase> <!-- assertTestA -->
</testsuite> <!-- packageExample -->
